[Settings]
  ID = "hcp-alloderm"

[build]
  functions = "functions"
  publish = "src"
  command = "npm run build"

[dev]
  publish = "src"

[[redirects]]
  from = "/AllodermDownloadPDF/PDFDownload"
  to = "http://localhost:8888/.netlify/functions/pdfdownload"
  status = 200
  force = true