[Settings]
  ID = "hcp-alloderm"

[build]
  functions = "functions"
  publish = "src"
  command = "npm run build"


[functions]
  included_files = ["function-assets/*"]

[dev]
  publish = "src"

[[redirects]]
  from = "/AllodermDownloadPDF/PDFDownload"
  to = "/.netlify/functions/pdfdownload"
  status = 200
  force = true